[opener]
edit = [
	{ run = 'nvim', block = true,  desc = "nvim (block)",   for = "windows" },
]
extract = [
	{ run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

[plugin]

prepend_preloaders = [
  { mime = "video/*", run = "video-ffmpeg" },
]

prepend_previewers = [
	# Archive previewer
	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
  { mime = "audio/*",   run = "exifaudio"},
  { mime = "video/*", run = "video-ffmpeg" },
  { name = "*.ipynb", run = "nbpreview" },
]
